version: "3"

services:
  api:
    build: .
    container_name: "go-barber-api"
    ports:
      - "3333:3333"
    restart: on-failure
    environment:
      - APP_URL=${APP_URL}
      - APP_SECRET=${APP_SECRET}
      - DB_HOST=postgre-gobarber
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - MONGO_HOST=mongo-gobarber
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=redis-gobarber
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    networks:
      - go-barber-network
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres
    container_name: postgre-gobarber
    restart: on-failure
    volumes:
      - postgre-gobarber-data:/data
    networks:
      - go-barber-network
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}

  mongo:
    image: mongo
    container_name: mongo-gobarber
    restart: on-failure
    networks:
      - go-barber-network
    volumes:
      - mongo-gobarber-data:/data

  redis:
    image: redis
    container_name: redis-gobarber
    restart: on-failure
    networks:
      - go-barber-network
    volumes:
      - redis-gobarber-data:/data

volumes:
  postgre-gobarber-data:
  mongo-gobarber-data:
  redis-gobarber-data:

networks:
  go-barber-network:
